// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: verificar variáveis de ambiente
console.log('Environment variables:', {
  VITE_SUPABASE_URL: SUPABASE_URL,
  VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? 'Definida' : 'Não definida'
});

// Verificar se as variáveis estão definidas
if (!SUPABASE_URL) {
  console.error('VITE_SUPABASE_URL não está definida');
  console.error('Valores disponíveis:', import.meta.env);
  throw new Error('VITE_SUPABASE_URL is required');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY não está definida');
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY is required');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});